# Generated by Django 4.2.1 on 2023-06-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversionRateCurrency',
            fields=[
                ('conversionRateCurrencyId', models.AutoField(primary_key=True, serialize=False)),
                ('asOfDate', models.DateField()),
                ('countryOrigin', models.CharField(choices=[('USD', 'United States'), ('EUR', 'Italy'), ('EUR', 'Spain'), ('MXN', 'Mexico'), ('CAN', 'Canada')], max_length=3)),
                ('countryArrival', models.CharField(choices=[('USD', 'United States'), ('EUR', 'Italy'), ('EUR', 'Spain'), ('MXN', 'Mexico'), ('CAN', 'Canada')], max_length=3)),
                ('exchangeRate', models.DecimalField(choices=[('USD', 'United States'), ('EUR', 'Italy'), ('EUR', 'Spain'), ('MXN', 'Mexico'), ('CAN', 'Canada')], decimal_places=2, default=1.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('vacationId', models.AutoField(primary_key=True, serialize=False)),
                ('countryOrigin', models.CharField(choices=[('USD', 'United States'), ('EUR', 'Italy'), ('EUR', 'Spain'), ('MXN', 'Mexico'), ('CAN', 'Canada')], default='USD', max_length=3)),
                ('countryArrival', models.CharField(choices=[('USD', 'United States'), ('EUR', 'Italy'), ('EUR', 'Spain'), ('MXN', 'Mexico'), ('CAN', 'Canada')], default='MXN', max_length=3)),
                ('conversionFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='costCategory',
            fields=[
                ('costCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('costCategory', models.CharField(choices=[('F', 'Flight'), ('C', 'Car/Vehicle Transportation'), ('O', 'Food'), ('L', 'Lodging'), ('M', 'Miscellaneous/Extras'), ('A', 'Activities')], default='M', max_length=1)),
                ('originCostAmount', models.DecimalField(decimal_places=2, default=100.0, max_digits=15)),
                ('latestConversionRate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('arrivalCostAmount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Converter.vacation')),
            ],
        ),
    ]
