# Generated by Django 4.2.1 on 2023-06-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Converter', '0002_alter_costcategory_costcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcategory',
            name='arrivalCostAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='costcategory',
            name='costCategory',
            field=models.CharField(choices=[('F', 'Flight'), ('C', 'Car/Vehicle Transportation'), ('O', 'Food'), ('L', 'Lodging'), ('M', 'Miscellaneous/Extras'), ('A', 'Activities')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='costcategory',
            name='latestConversionRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='costcategory',
            name='originCostAmount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=15),
        ),
    ]
