# Generated by Django 4.2.1 on 2023-06-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Converter', '0004_alter_costcategory_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcategory',
            name='latestConversionRate',
        ),
        migrations.AddField(
            model_name='vacation',
            name='latestConversionRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
